#creation of alist
prog_lang=['c','c++','java','pytho','flutter','cobalt','dart','javascript']
print(prog_lang)
print(type(prog_lang))
print("_______________________________________________________________________")
print("accessing the list of positive elements :")
print(prog_lang[0])
print(prog_lang[1])
print(prog_lang[2])
print(prog_lang[3])
print(prog_lang[4])
print(prog_lang[5])
print(prog_lang[6])
print(prog_lang[7])
print("_____________________________________________________________________")
print("accessing the list of negative elements :")
print(prog_lang[-7])
print(prog_lang[-6])
print(prog_lang[-5])
print(prog_lang[-4])
print(prog_lang[-3])
print(prog_lang[-2])
print(prog_lang[-1])
