cartoons=['tom and jerry','hiedi','dora','krishna aur balarm','sinchan','ben-ten','chota beem']
print(cartoons)
print("after appending an element")
cartoons.append('oggy and cockroaches')
print(cartoons)
print("after inserting the element")
cartoons.insert(2,'roll number 21')
print(cartoons)
print("afterr popping the element")
cartoons.pop()
print(cartoons)
cartoons.pop(3)
cartoons.remove('sinchan')
print(cartoons)
print(cartoons.index('tom and jerry'))
print("after reverrsing the element")
cartoons.reverse()
print(cartoons)