emp_name=input("enter the emp_name :")
emp_desg=input("enter the emp_desg :")
emp_salary=int(input("enter the emp_salary :"))
emp_specialallowance=int(input("enter the emp_special allowances :"))
emp_bonus=int(input("enter the emp_bonus :"))
print("employee salary card....")
print("_____________________________________________________")
print("emp_name :",emp_name)
print("emp_desg :",emp_desg)
print("emp_salary:",emp_salary)
print("emp_special allowances :",emp_specialallowance)
print("emp_bonus :",emp_bonus)
print("________________________________________")
gross_monthly_salary=(emp_salary+emp_specialallowance)
print("gross_monthly_salary :",gross_monthly_salary)
gross_annual_salary=(gross_monthly_salary+emp_bonus)
print("gross_annual_salary :",gross_annual_salary)


