amount=int(input("enter the principl_amount :"))
interest=int(input("enter the interest_amount :"))
time=int(input("enter the time :"))
print("details")
print("_____________________________________________")
print("amount :",amount)
print("interest :",interest)
print("time :",time)
simpleinterest=((amount*interest*time)/100)
print("simple interest is :",simpleinterest)